# tests/test_output_dir.py
"""Output folders never mix runs: ownership marker, clean re-runs, refusals that change nothing."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict

import pytest

from calmoji.cli import main, parse_args
from calmoji.constants import OUTPUT_MARKER_NAME, OUTPUT_MARKER_TEXT
from calmoji.output_dir import OutputDirError, check_output_dir, default_output_dir, prepare_output_dir

MARKER = OUTPUT_MARKER_NAME


def run(outdir: Path, *extra: str, year: int = 2027, alignment: str = "academic") -> None:
    main([f"--year={year}", f"--calendar-alignment={alignment}", f"--output-dir={outdir}", *extra])


def snapshot(root: Path) -> Dict[str, object]:
    """Every path under root, with the bytes of files: equal snapshots mean nothing changed."""
    if not root.exists():
        return {"<missing>": None}
    return {
        p.relative_to(root).as_posix() + ("/" if p.is_dir() else ""): (None if p.is_dir() else p.read_bytes())
        for p in sorted(root.rglob("*"))
    }


def focus_files(outdir: Path):
    return sorted(p.name for p in (outdir / "focus").iterdir())


# -----------------------------------------------------------------------------
# The marker
# -----------------------------------------------------------------------------


def test_a_run_writes_the_marker_with_fixed_content(tmp_path):
    run(tmp_path / "out")
    marker = tmp_path / "out" / MARKER
    assert marker.read_text(encoding="utf-8") == OUTPUT_MARKER_TEXT
    assert OUTPUT_MARKER_TEXT == "Generated by calmoji. Re-running calmoji replaces this folder's calmoji files.\n"


def test_an_empty_existing_folder_is_fine(tmp_path):
    out = tmp_path / "out"
    out.mkdir()
    run(out)
    assert (out / MARKER).is_file() and (out / "focus").is_dir()


# -----------------------------------------------------------------------------
# Re-running
# -----------------------------------------------------------------------------


def test_academic_then_calendar_into_one_folder_leaves_exactly_twelve_focus_files(tmp_path):
    out = tmp_path / "out"
    run(out, alignment="academic")
    assert len(focus_files(out)) == 12 and "focus_2027-09.ics" in focus_files(out)

    run(out, alignment="calendar")

    assert focus_files(out) == [f"focus_2027-{m:02d}.ics" for m in range(1, 13)]
    assert len(sorted((out / "meetings").iterdir())) == 12
    assert sorted(p.name for p in out.glob("*.ics")) == ["emoji_clock_2027.ics", "seasons_2027.ics"]


def test_a_rerun_with_no_meetings_leaves_no_meetings_folder(tmp_path):
    out = tmp_path / "out"
    run(out)
    assert (out / "meetings").is_dir()

    run(out, "--no-meetings")

    assert not (out / "meetings").exists()
    assert (out / "focus").is_dir()


def test_a_rerun_with_no_ebi48_leaves_no_emoji_clock(tmp_path):
    out = tmp_path / "out"
    run(out)
    run(out, "--no-ebi48")
    assert not list(out.glob("emoji_clock_*"))


def test_rerunning_the_same_command_gives_the_same_folder(tmp_path):
    out = tmp_path / "out"
    run(out)
    first = snapshot(out)
    run(out)
    assert snapshot(out) == first


def test_a_rerun_removes_stale_top_level_ics_files_from_older_versions(tmp_path):
    out = tmp_path / "out"
    run(out)
    (out / "semester_phases_2027.ics").write_text("old", encoding="utf-8")
    (out / "ebi48_layer_2027.ics").write_text("old", encoding="utf-8")

    run(out)

    assert not (out / "semester_phases_2027.ics").exists()
    assert not (out / "ebi48_layer_2027.ics").exists()


def test_an_explicit_output_dir_is_used_as_given(tmp_path):
    out = tmp_path / "exactly" / "here"
    run(out)
    assert (out / "seasons_2027.ics").is_file()
    assert not (out / "2027").exists()


def test_the_year_can_change_between_runs(tmp_path):
    out = tmp_path / "out"
    run(out, year=2027)
    run(out, year=2028)
    assert sorted(p.name for p in out.glob("*.ics")) == ["emoji_clock_2028.ics", "seasons_2028.ics"]


# -----------------------------------------------------------------------------
# Refusals: nothing written, nothing deleted
# -----------------------------------------------------------------------------


def test_a_foreign_non_empty_folder_is_refused_and_left_alone(tmp_path):
    out = tmp_path / "my-photos"
    (out / "2027").mkdir(parents=True)
    (out / "2027" / "holiday.jpg").write_bytes(b"jpeg")
    (out / "notes.txt").write_text("keep me", encoding="utf-8")
    before = snapshot(out)

    with pytest.raises(SystemExit) as excinfo:
        run(out)

    message = str(excinfo.value)
    assert message.startswith("error:") and str(out) in message
    assert "empty folder" in message and "--output-dir" in message
    assert MARKER in message  # says why: it has no marker
    assert snapshot(out) == before


def test_a_foreign_folder_holding_ics_files_is_still_refused(tmp_path):
    out = tmp_path / "my-calendars"
    out.mkdir()
    (out / "family.ics").write_text("BEGIN:VCALENDAR\nEND:VCALENDAR\n", encoding="utf-8")
    before = snapshot(out)

    with pytest.raises(SystemExit):
        run(out)

    assert snapshot(out) == before


def test_a_marked_folder_with_an_unexpected_file_is_refused_and_nothing_is_deleted(tmp_path):
    out = tmp_path / "out"
    run(out)
    (out / "my-notes.txt").write_text("not calmoji's", encoding="utf-8")
    (out / "focus" / "extra.txt").write_text("not calmoji's either", encoding="utf-8")
    (out / "photos").mkdir()
    before = snapshot(out)

    with pytest.raises(SystemExit) as excinfo:
        run(out, "--no-meetings")

    message = str(excinfo.value)
    assert "my-notes.txt" in message and "focus/extra.txt" in message and "photos/" in message
    assert "calmoji won't delete anything" in message
    assert snapshot(out) == before  # the old meetings/ and focus files are all still there


def test_a_marked_folder_with_a_symlinked_owned_folder_is_refused(tmp_path):
    out = tmp_path / "out"
    run(out)
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    (elsewhere / "precious.ics").write_text("precious", encoding="utf-8")
    for owned in ("focus", "meetings"):
        for child in (out / owned).iterdir():
            child.unlink()
        (out / owned).rmdir()
    os.symlink(elsewhere, out / "focus")

    with pytest.raises(SystemExit):
        run(out)

    assert (elsewhere / "precious.ics").read_text(encoding="utf-8") == "precious"


def test_a_path_that_is_a_file_is_refused(tmp_path):
    target = tmp_path / "out"
    target.write_text("a file, not a folder", encoding="utf-8")
    with pytest.raises(SystemExit) as excinfo:
        run(target)
    assert "not a folder" in str(excinfo.value)
    assert target.read_text(encoding="utf-8") == "a file, not a folder"


def test_prepare_output_dir_raises_a_value_error_before_changing_anything(tmp_path):
    out = tmp_path / "foreign"
    out.mkdir()
    (out / "x.txt").write_text("x", encoding="utf-8")
    before = snapshot(out)
    with pytest.raises(OutputDirError):
        prepare_output_dir(out)
    assert issubclass(OutputDirError, ValueError)
    assert snapshot(out) == before


def test_check_output_dir_is_read_only_and_names_the_reason(tmp_path):
    assert check_output_dir(tmp_path / "missing") is None
    empty = tmp_path / "empty"
    empty.mkdir()
    assert check_output_dir(empty) is None
    assert snapshot(empty) == {}

    foreign = tmp_path / "foreign"
    foreign.mkdir()
    (foreign / "a").write_text("a", encoding="utf-8")
    assert "didn't create it" in (check_output_dir(foreign) or "")


# -----------------------------------------------------------------------------
# macOS Finder litter is looked past (neither refused nor deleted)
# -----------------------------------------------------------------------------


def test_ds_store_does_not_make_a_folder_foreign_or_unexpected(tmp_path):
    only_litter = tmp_path / "just-opened-in-finder"
    only_litter.mkdir()
    (only_litter / ".DS_Store").write_bytes(b"finder")
    run(only_litter)  # counts as empty
    assert (only_litter / MARKER).is_file()

    run(only_litter)  # and a marked folder with one in it is not refused either
    assert (only_litter / ".DS_Store").read_bytes() == b"finder"  # left exactly as it was


# -----------------------------------------------------------------------------
# --dry-run never touches the filesystem
# -----------------------------------------------------------------------------


def test_dry_run_into_a_missing_folder_creates_nothing(tmp_path):
    out = tmp_path / "out"
    run(out, "--dry-run")
    assert not out.exists()


def test_dry_run_leaves_an_empty_folder_empty(tmp_path):
    out = tmp_path / "out"
    out.mkdir()
    run(out, "--dry-run")
    assert snapshot(out) == {}


def test_dry_run_leaves_a_marked_folder_untouched(tmp_path):
    out = tmp_path / "out"
    run(out)
    before = snapshot(out)
    run(out, "--dry-run", "--no-meetings", year=2028)
    assert snapshot(out) == before


def test_dry_run_into_a_foreign_folder_warns_and_changes_nothing(tmp_path, capsys):
    out = tmp_path / "foreign"
    out.mkdir()
    (out / "mine.txt").write_text("mine", encoding="utf-8")
    before = snapshot(out)

    run(out, "--dry-run")

    assert "A real run would refuse" in capsys.readouterr().out
    assert snapshot(out) == before


def test_dry_run_with_the_default_path_writes_nothing(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    main(["--year=2027", "--dry-run"])
    assert list(tmp_path.iterdir()) == []


# -----------------------------------------------------------------------------
# The default path
# -----------------------------------------------------------------------------


def test_the_default_output_dir_is_output_year_alignment(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    main(["--year=2027"])
    main(["--year=2027", "--calendar-alignment=calendar"])
    main(["--year=2028", "--calendar-alignment=calendar"])

    assert (tmp_path / "output" / "2027" / "academic" / "seasons_2027.ics").is_file()
    assert (tmp_path / "output" / "2027" / "calendar" / "seasons_2027.ics").is_file()
    assert (tmp_path / "output" / "2028" / "calendar" / "seasons_2028.ics").is_file()
    # runs for different years and alignments no longer mix
    assert len(focus_files(tmp_path / "output" / "2027" / "academic")) == 12
    assert len(focus_files(tmp_path / "output" / "2027" / "calendar")) == 12
    assert not (tmp_path / "output" / "seasons_2027.ics").exists()


def test_the_default_is_computed_from_year_and_alignment():
    assert default_output_dir(2027, "academic") == Path("output") / "2027" / "academic"
    assert parse_args(["--year=2027"]).output_dir is None
    assert parse_args(["--year=2027", "--output-dir=somewhere"]).output_dir == Path("somewhere")


def test_help_describes_the_default_and_the_marker(capsys):
    with pytest.raises(SystemExit):
        parse_args(["--help"])
    text = " ".join(capsys.readouterr().out.split())
    assert "output/<year>/<alignment>/" in text
    assert ".calmoji-output" in text
