#!/usr/bin/env python3
"""
build_bundle.py — build the release archives that get attached to a GitHub Release.

    python3 scripts/build_bundle.py --out dist

For every year x alignment this generates calmoji's calendars into

    <out>/v<version>/<year>/<alignment>/

checks that no file is over the size budget (MAX_EVENTS_PER_FILE events and
MAX_BYTES_PER_FILE bytes, see calmoji.constants), then adds MANIFEST.sha256 (the
SHA-256 of every .ics) and a README.md, and packs
the whole v<version>/ folder into

    <out>/calmoji-artifacts-v<version>.zip
    <out>/calmoji-artifacts-v<version>.tar.gz

The version comes from the installed package metadata (so run it from a venv
where `python3 -m pip install -e .` has been done), which is why there is no
--version flag.

How the calendars are generated: this calls calmoji.cli.main() in-process (no
subprocess) with the CLI's default options (meetings, focus blocks and EBI48 on,
no Oceania). That is the CLI's own code path, so the bundle's per-year layout is
the CLI's layout by construction.

Determinism: nothing here reads the clock, hostname, user or random state.
Entries are sorted; zip timestamps are 1980-01-01; tar mtimes, uids and gids are
0 with empty owner names; the gzip header carries mtime 0 and no file name;
modes are fixed. Running it twice on the same machine gives byte-identical
archives. Across machines only the .ics files and MANIFEST.sha256 are promised
to be identical: different zlib builds can compress the same bytes differently.

Standard library only; runs on Python 3.9 and newer.
"""

from __future__ import annotations

import argparse
import contextlib
import gzip
import hashlib
import io
import re
import shutil
import stat
import sys
import tarfile
import zipfile
from pathlib import Path
from typing import List, NamedTuple, Optional, Sequence, Tuple

try:
    from calmoji import __version__
    from calmoji.calendar_config import ALIGNMENT_MODES
    from calmoji.cli import main as calmoji_main
    from calmoji.constants import MAX_BYTES_PER_FILE, MAX_EVENTS_PER_FILE, OUTPUT_MARKER_NAME
    from calmoji.ics_writer import IcsBudgetError
except ImportError as exc:  # pragma: no cover -- only when calmoji isn't installed
    raise SystemExit(
        f"error: cannot import calmoji ({exc}).\nInstall it first, from the repo root: python3 -m pip install -e ."
    ) from exc

SCRIPT_DIR = Path(__file__).resolve().parent
README_TEMPLATE = SCRIPT_DIR / "bundle_README.md.in"

# 2026-2036, not later: Proton Calendar only accepts events up to the end of 2037, and the
# 2037 academic year runs into 2038. Everything we ship should import everywhere. Any year
# can still be generated by hand.
DEFAULT_YEARS = "2026-2036"
DEFAULT_ALIGNMENTS = "academic,calendar"
DEFAULT_OUT = "dist"

# Typo guard for --years (for example 2026-2399 instead of 2026-2039).
MIN_YEAR = 1900
MAX_YEAR = 2100

MANIFEST_NAME = "MANIFEST.sha256"
README_NAME = "README.md"

ZIP_DATE_TIME = (1980, 1, 1, 0, 0, 0)
COMPRESS_LEVEL = 9
FILE_MODE = 0o644
DIR_MODE = 0o755

_YEARS_RE = re.compile(r"^(\d{4})(?:\s*[-–]\s*(\d{4}))?$")


class FileStats(NamedTuple):
    path: str  # relative to the bundle folder
    events: int
    size: int  # bytes


class BundleBudgetError(ValueError):
    """A generated file is over the size budget."""


class BuildResult(NamedTuple):
    version: str
    years: List[int]
    alignments: List[str]
    bundle_dir: Path
    zip_path: Path
    tar_path: Path
    ics_count: int
    file_count: int
    largest_by_events: FileStats
    largest_by_size: FileStats
    zip_sha256: str
    tar_sha256: str


# ── Argument parsing ────────────────────────────────────────────────────────


def parse_years(spec: str) -> List[int]:
    """
    Parse --years: a single year ('2030') or an inclusive range ('2026-2039').

    Raises argparse.ArgumentTypeError on anything else, on a reversed range, and
    on years outside MIN_YEAR..MAX_YEAR.
    """
    match = _YEARS_RE.match(spec.strip())
    if not match:
        raise argparse.ArgumentTypeError(f"invalid years {spec!r}: expected YYYY or YYYY-YYYY, for example 2026-2039")

    first = int(match.group(1))
    last = int(match.group(2)) if match.group(2) else first

    if first > last:
        raise argparse.ArgumentTypeError(f"invalid years {spec!r}: {first} is after {last}")
    for year in (first, last):
        if not MIN_YEAR <= year <= MAX_YEAR:
            raise argparse.ArgumentTypeError(f"invalid years {spec!r}: {year} is outside {MIN_YEAR}-{MAX_YEAR}")

    return list(range(first, last + 1))


def parse_alignments(spec: str) -> List[str]:
    """Parse --alignments: comma-separated names known to calmoji, duplicates dropped, order kept."""
    names = [part.strip() for part in spec.split(",")]
    if not all(names):
        raise argparse.ArgumentTypeError(f"invalid alignments {spec!r}: expected names separated by commas")

    unknown = [name for name in names if name not in ALIGNMENT_MODES]
    if unknown:
        raise argparse.ArgumentTypeError(
            f"unknown alignment {', '.join(repr(u) for u in unknown)}; choose from {', '.join(sorted(ALIGNMENT_MODES))}"
        )

    return list(dict.fromkeys(names))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="build_bundle.py",
        description="Build the calmoji release archives (zip and tar.gz) for a GitHub Release.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(DEFAULT_OUT),
        help=f"output directory (default: {DEFAULT_OUT}/)",
    )
    parser.add_argument(
        "--years",
        type=parse_years,
        default=parse_years(DEFAULT_YEARS),
        metavar="YYYY[-YYYY]",
        help=f"year or inclusive range of years (default: {DEFAULT_YEARS})",
    )
    parser.add_argument(
        "--alignments",
        type=parse_alignments,
        default=parse_alignments(DEFAULT_ALIGNMENTS),
        metavar="A[,B...]",
        help=f"comma-separated alignments (default: {DEFAULT_ALIGNMENTS})",
    )
    return parser


# ── Building blocks ─────────────────────────────────────────────────────────


def generate_year(year: int, alignment: str, outdir: Path) -> None:
    """Generate one year x alignment with the CLI's default options, quietly."""
    argv = [f"--year={year}", f"--calendar-alignment={alignment}", f"--output-dir={outdir}"]
    with contextlib.redirect_stdout(io.StringIO()):
        calmoji_main(argv)


def sha256_hex(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def ics_files(bundle_dir: Path) -> List[str]:
    """Every .ics under bundle_dir as a sorted POSIX path relative to it."""
    return sorted(p.relative_to(bundle_dir).as_posix() for p in bundle_dir.rglob("*.ics") if p.is_file())


def measure_files(bundle_dir: Path) -> List[FileStats]:
    """Event count and size in bytes of every .ics under bundle_dir, sorted by path."""
    stats = []
    for rel in ics_files(bundle_dir):
        data = (bundle_dir / rel).read_bytes()
        stats.append(FileStats(rel, data.count(b"\nBEGIN:VEVENT\r\n"), len(data)))
    return stats


def check_budget(stats: Sequence[FileStats]) -> None:
    """Fail if any file is over MAX_EVENTS_PER_FILE events or MAX_BYTES_PER_FILE bytes."""
    over = [
        f"{f.path}: {f.events} events, {f.size:,} bytes"
        for f in stats
        if f.events > MAX_EVENTS_PER_FILE or f.size > MAX_BYTES_PER_FILE
    ]
    if over:
        raise BundleBudgetError(
            f"{len(over)} file(s) over the budget of {MAX_EVENTS_PER_FILE} events and {MAX_BYTES_PER_FILE:,} bytes:\n  "
            + "\n  ".join(over)
        )


def write_manifest(bundle_dir: Path) -> int:
    """
    Write MANIFEST.sha256: '<sha256>  ./<path>' for every .ics, sorted by path.

    That is the format both `shasum -a 256 -c` and `sha256sum -c` read, run from
    inside bundle_dir. Returns the number of entries.
    """
    paths = ics_files(bundle_dir)
    lines = [f"{sha256_hex(bundle_dir / rel)}  ./{rel}\n" for rel in paths]
    (bundle_dir / MANIFEST_NAME).write_bytes("".join(lines).encode("utf-8"))
    return len(paths)


def render_readme(template: str, version: str, years: Sequence[int]) -> str:
    """Substitute @VERSION@, @YEARS@ and the size budget (@MAX_EVENTS@, @MAX_KIB@) in the README template."""
    span = str(years[0]) if years[0] == years[-1] else f"{years[0]}–{years[-1]}"
    text = (
        template.replace("@VERSION@", version)
        .replace("@YEARS@", span)
        .replace("@MAX_EVENTS@", str(MAX_EVENTS_PER_FILE))
        .replace("@MAX_KIB@", str(MAX_BYTES_PER_FILE // 1024))
    )

    leftover = sorted(set(re.findall(r"@[A-Z][A-Z_]*@", text)))
    if leftover:
        raise ValueError(f"unfilled placeholders in README template: {', '.join(leftover)}")
    return text


def write_readme(bundle_dir: Path, version: str, years: Sequence[int]) -> None:
    template = README_TEMPLATE.read_text(encoding="utf-8")
    (bundle_dir / README_NAME).write_bytes(render_readme(template, version, years).encode("utf-8"))


def archive_entries(bundle_dir: Path) -> List[Tuple[str, bool]]:
    """
    Everything that goes into the archives as (path relative to bundle_dir's
    parent, is_dir), sorted by path. A directory sorts before its contents.

    Refuses to archive anything that isn't a generated .ics, the manifest or
    the README (a stray .DS_Store, say).
    """
    root = bundle_dir.parent
    allowed = set(ics_files(bundle_dir)) | {MANIFEST_NAME, README_NAME}

    entries = [(bundle_dir.name, True)]
    for path in bundle_dir.rglob("*"):
        rel = path.relative_to(bundle_dir).as_posix()
        if path.is_dir():
            entries.append((path.relative_to(root).as_posix(), True))
        elif rel in allowed:
            entries.append((path.relative_to(root).as_posix(), False))
        else:
            raise ValueError(f"unexpected file in bundle: {rel}")

    return sorted(entries)


def write_zip(bundle_dir: Path, dest: Path) -> None:
    """Zip bundle_dir (as a top-level v<version>/ folder): sorted, fixed timestamp, fixed permissions."""
    root = bundle_dir.parent
    with zipfile.ZipFile(dest, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=COMPRESS_LEVEL) as zf:
        for rel, is_dir in archive_entries(bundle_dir):
            if is_dir:
                info = zipfile.ZipInfo(rel + "/", date_time=ZIP_DATE_TIME)
                info.compress_type = zipfile.ZIP_STORED
                info.external_attr = ((stat.S_IFDIR | DIR_MODE) << 16) | 0x10  # 0x10: MS-DOS directory flag
                data = b""
            else:
                info = zipfile.ZipInfo(rel, date_time=ZIP_DATE_TIME)
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = (stat.S_IFREG | FILE_MODE) << 16
                data = (root / rel).read_bytes()
            info.create_system = 3  # Unix, whatever platform builds it
            zf.writestr(info, data, compresslevel=COMPRESS_LEVEL)


def write_tar_gz(bundle_dir: Path, dest: Path) -> None:
    """
    Tar+gzip bundle_dir: sorted, mtime 0, uid/gid 0 with empty owner names, fixed
    modes. The gzip header is written by hand-built GzipFile(filename='',
    mtime=0), because tarfile's own 'w:gz' stamps the current time and the file name.
    """
    root = bundle_dir.parent
    with open(dest, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", compresslevel=COMPRESS_LEVEL, fileobj=raw, mtime=0) as gz:
            with tarfile.open(fileobj=gz, mode="w", format=tarfile.PAX_FORMAT, encoding="utf-8") as tar:
                for rel, is_dir in archive_entries(bundle_dir):
                    info = tarfile.TarInfo(rel)
                    info.mtime = 0
                    info.uid = 0
                    info.gid = 0
                    info.uname = ""
                    info.gname = ""
                    if is_dir:
                        info.type = tarfile.DIRTYPE
                        info.mode = DIR_MODE
                        tar.addfile(info)
                    else:
                        data = (root / rel).read_bytes()
                        info.size = len(data)
                        info.mode = FILE_MODE
                        tar.addfile(info, io.BytesIO(data))


def build_bundle(
    out: Path,
    years: Sequence[int],
    alignments: Sequence[str],
    *,
    version: Optional[str] = None,
) -> BuildResult:
    """Generate every year x alignment, then the manifest, README and both archives."""
    version = __version__ if version is None else version
    out.mkdir(parents=True, exist_ok=True)

    bundle_dir = out / f"v{version}"
    if bundle_dir.exists():
        if not bundle_dir.is_dir() or bundle_dir.is_symlink():
            raise ValueError(f"{bundle_dir} exists and is not a directory")
        shutil.rmtree(bundle_dir)  # rebuild from scratch: no stale files from an earlier run

    for year in years:
        for alignment in alignments:
            generate_year(year, alignment, bundle_dir / str(year) / alignment)

    # The CLI marks each folder it writes as its own. The marker is for people who generate by
    # hand; it is not part of the release, so it never gets into the manifest or the archives.
    for marker in sorted(bundle_dir.rglob(OUTPUT_MARKER_NAME)):
        marker.unlink()

    stats = measure_files(bundle_dir)
    check_budget(stats)

    ics_count = write_manifest(bundle_dir)
    write_readme(bundle_dir, version, years)

    zip_path = out / f"calmoji-artifacts-v{version}.zip"
    tar_path = out / f"calmoji-artifacts-v{version}.tar.gz"
    write_zip(bundle_dir, zip_path)
    write_tar_gz(bundle_dir, tar_path)

    return BuildResult(
        version=version,
        years=list(years),
        alignments=list(alignments),
        bundle_dir=bundle_dir,
        zip_path=zip_path,
        tar_path=tar_path,
        ics_count=ics_count,
        file_count=ics_count + 2,  # + MANIFEST.sha256 and README.md
        largest_by_events=max(stats, key=lambda f: (f.events, f.size, f.path)),
        largest_by_size=max(stats, key=lambda f: (f.size, f.events, f.path)),
        zip_sha256=sha256_hex(zip_path),
        tar_sha256=sha256_hex(tar_path),
    )


def format_size(size: int) -> str:
    return f"{size:,} bytes ({size / (1024 * 1024):.1f} MiB)"


def print_summary(result: BuildResult) -> None:
    first, last = result.years[0], result.years[-1]
    print(f"calmoji v{result.version} release bundle: {first}-{last}, {', '.join(result.alignments)}")
    print(f"Files: {result.ics_count} .ics (+ {MANIFEST_NAME} and {README_NAME}: {result.file_count} files in all)")
    print(f"Folder: {result.bundle_dir}")
    print(f"Budget per file: {MAX_EVENTS_PER_FILE} events and {MAX_BYTES_PER_FILE:,} bytes")
    most, biggest = result.largest_by_events, result.largest_by_size
    print(f"Largest file by events: {most.events} events, {most.size:,} bytes ({most.path})")
    print(f"Largest file by size: {biggest.events} events, {biggest.size:,} bytes ({biggest.path})")
    for path in (result.zip_path, result.tar_path):
        print(f"{path.name}: {format_size(path.stat().st_size)}")
    print()
    print("SHA-256 (paste into the release notes):")
    print(f"{result.zip_sha256}  {result.zip_path.name}")
    print(f"{result.tar_sha256}  {result.tar_path.name}")


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    if "+local" in __version__:
        print(
            f"error: calmoji reports version {__version__}, i.e. it is not installed.\n"
            "Install it first, from the repo root: python3 -m pip install -e .",
            file=sys.stderr,
        )
        return 1

    try:
        result = build_bundle(args.out, args.years, args.alignments)
    except (BundleBudgetError, IcsBudgetError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print_summary(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
